models/contato.py
from utils.db import db

class Contato(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(40))
    email = db.Column(db.String(40))
    telefone = db.Column(db.String(20))

    def __init__(self, nome, email, telefone):
        self.nome = nome
        self.email = email
        self.telefone = telefone

app.py
from flask import Flask, app
from routes.contatos import contatos
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.secret_key = 'masterpass'
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://jeremias:2132@localhost/contatosdb'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(contatos)

routes/contatos.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contato import Contato
from utils.db import db


contatos = Blueprint('contatos', __name__)


@contatos.route('/')
def index():
    contatos = Contato.query.all()
    return render_template('index.html', contatos=contatos)


@contatos.route('/novo', methods=['POST'])
def add_contato():
    nome = request.form['nome']
    email = request.form['email']
    telefone = request.form['telefone']

    novo_contato = Contato(nome, email, telefone)

    db.session.add(novo_contato)
    db.session.commit()

    flash("Contato adicionado!")

    return redirect(url_for('contatos.index')) 


@contatos.route('/atualiza/<id>', methods = ['POST', 'GET'])
def upd_contato(id):
    contato = Contato.query.get(id)
    
    if request.method == 'POST':
        contato = Contato.query.get(id)
        contato.nome = request.form["nome"]
        contato.email = request.form["email"]
        contato.telefone = request.form["telefone"]

        db.session.commit()

        flash("Contato atualizado!")

        return redirect(url_for("contatos.index"))

    return render_template('update.html', contato=contato)


@contatos.route('/remove/<id>')
def del_contato(id):
    contato = Contato.query.get(id)
    db.session.delete(contato)
    db.session.commit()

    flash("Contato removido!")

    return redirect(url_for('contatos.index'))   


@contatos.route('/sobre')
def sobre():
    return render_template('sobre.html')

templates/index.html
 {% extends 'layout.html' %}   

 {% block body %}

    {% with messages = get_flashed_messages() %}

        {% if messages %}
            {%  for message in messages %}
                {{message}}
            {% endfor %}
        {% endif %}

    {% endwith %}

    <div class="row">
        <div class="col-md-5">
            {% include('partials/_contatoForm.html') %}
        </div>

        <div class="col-md-7">
            <div>
                {% for contato in contatos %}
                
                <div>
                    <h5>{{contato.nome}}</h5>
                    <div>
                        <a href="{{ url_for('contatos.upd_contato', id=contato.id) }}"> Atualizar </a>
                        <a href="{{ url_for('contatos.del_contato', id=contato.id) }}"> Remover </a>
                    </div>
                    <p>{{contato.email}}</p>
                    <p>{{contato.telefone}}</p>
                </div>
            
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Flask CRUD</title>
</head>
<body>
    
    {% include('partials/_navbar.html') %}

    <div class="container p-2">
        {% block body %}

        {%  endblock %}
    </div>
 
</body>
</html>

templates/partials/_contatoForm.html
<form action="/novo" method="POST" class="card bg-dark text-light">
    <div class="card-body p-4">
        <div class="mb-3">
            <label for="nome">Nome Completo:</label>
            <input type="text" name="nome" placeholder="Informe o nome"
                class="form-control rounded-0 bg-dark border-0 text-white" required>
        </div>
        <div class="mb-3">
            <label for="email">Email:</label>
            <input type="email" name="email" placeholder="Informe o email"
                class="form-control rounded-0 bg-dark border-0 text-white" required>
        </div>
        <div class="mb-3">
            <label for="telefone">Telefone:</label>
            <input type="tel" name="telefone" placeholder="Informe o telefone"
                class="form-control rounded-0 bg-dark border-0 text-white" required>
        </div>
    
        <button class="btn btn-primary">Adicionar</button>
    </div>

</form>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Flask CRUD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/sobre">Sobre</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/sobre.html
{% extends 'layout.html' %}

{% block body %}

    <h1>Sobre</h1>

    <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum natus ut deserunt voluptatem enim autem sint
        quae architecto odio quos odit velit fugiat tenetur, facilis voluptas, laudantium eaque, recusandae impedit
        pariatur! Ipsa, fugiat voluptatum quis, temporibus odio, cupiditate illum provident labore perspiciatis
        reiciendis voluptates officia corporis vero natus est aut error quisquam eius. Itaque veniam consequatur ut hic,
        at nam blanditiis voluptatem corporis provident amet quo, repudiandae sit beatae excepturi? Deleniti,
        blanditiis, expedita saepe obcaecati corporis at repellendus placeat similique, dolores dignissimos deserunt
        quaerat natus culpa voluptatibus iusto! In, inventore vel temporibus incidunt quis doloribus enim et pariatur
        molestias iure?
    </p>

{% endblock %}

templates/update.html
{% extends 'layout.html' %}

{% block body %}

<div class="row">
    <div class="col-md-5">

            <form action="/atualiza/{{contato.id}}" method="POST" class="card bg-dark text-light">
                <div class="card-body p-4">
                    <div class="mb-3">
                        <label for="nome">Nome Completo:</label>
                        <input type="text" name="nome" placeholder="Informe o nome"
                            class="form-control rounded-0 bg-dark border-0 text-white" value={{contato.nome}} required> 
                    </div>
                    <div class="mb-3">
                        <label for="email">Email:</label>
                        <input type="email" name="email" placeholder="Informe o email"
                            class="form-control rounded-0 bg-dark border-0 text-white" value={{contato.email}} required>
                    </div>
                    <div class="mb-3">
                        <label for="telefone">Telefone:</label>
                        <input type="tel" name="telefone" placeholder="Informe o telefone"
                            class="form-control rounded-0 bg-dark border-0 text-white" value={{contato.telefone}} required>
                    </div>
                
                    <button class="btn btn-primary">Salvar</button>
                </div>
            
            </form>
        </form>
    </div>
</div>

{% endblock %}